// <auto-generated />
using System;
using GradProject.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411190014_Extend_RunningActivity_Analytics_And_Splits")]
    partial class Extend_RunningActivity_Analytics_And_Splits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradProject.Domain.Entities.AchievementEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentRank")
                        .HasColumnType("integer");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PreviousRank")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RunId")
                        .HasColumnType("integer");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_AchievementEvents_DeduplicationKey");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_AchievementEvents_Type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AchievementEvents_UserId_Unread")
                        .HasFilter("\"ReadAtUtc\" IS NULL");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_AchievementEvents_UserId_OccurredAt");

                    b.ToTable("AchievementEvents", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PointsReward")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Badges_IsActive");

                    b.ToTable("Badges", t =>
                        {
                            t.HasCheckConstraint("CK_Badges_PointsReward_NonNegative", "\"PointsReward\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Challenges_CreatedByUserId");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_Challenges_EndDate");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Challenges_IsActive");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Challenges_StartDate");

                    b.HasIndex("IsCustom", "IsActive")
                        .HasDatabaseName("IX_Challenges_IsCustom_IsActive");

                    b.ToTable("Challenges", t =>
                        {
                            t.HasCheckConstraint("CK_Challenges_EndDate_GreaterThanOrEqual_StartDate", "\"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_Challenges_RewardPoints_NonNegative", "\"RewardPoints\" >= 0");

                            t.HasCheckConstraint("CK_Challenges_TargetValue_NonNegative", "\"TargetValue\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.ConsumedFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PortionG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("IX_ConsumedFoods_FoodId");

                    b.HasIndex("MealId")
                        .HasDatabaseName("IX_ConsumedFoods_MealId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConsumedFoods_UserId");

                    b.HasIndex("UserId", "ConsumedAt")
                        .HasDatabaseName("IX_ConsumedFoods_UserId_ConsumedAt");

                    b.ToTable("ConsumedFoods", t =>
                        {
                            t.HasCheckConstraint("CK_ConsumedFoods_PortionG_Positive", "\"PortionG\" > 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalorieTarget")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CarbTargetG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FatTargetG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ProteinTargetG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalCarbs")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalFat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TotalIntakeCalories")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalProtein")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailySummaries_Date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DailySummaries_UserId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailySummaries_UserId_Date");

                    b.ToTable("DailySummaries", t =>
                        {
                            t.HasCheckConstraint("CK_DailySummaries_TotalCarbs_NonNegative", "\"TotalCarbs\" >= 0");

                            t.HasCheckConstraint("CK_DailySummaries_TotalFat_NonNegative", "\"TotalFat\" >= 0");

                            t.HasCheckConstraint("CK_DailySummaries_TotalIntakeCalories_NonNegative", "\"TotalIntakeCalories\" >= 0");

                            t.HasCheckConstraint("CK_DailySummaries_TotalProtein_NonNegative", "\"TotalProtein\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CarbG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("DefaultPortionG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("FiberG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("Kcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("SodiumMg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SugarG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Foods_Category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Foods_Name");

                    b.ToTable("Foods", t =>
                        {
                            t.HasCheckConstraint("CK_Foods_CarbG_NonNegative", "\"CarbG\" >= 0");

                            t.HasCheckConstraint("CK_Foods_DefaultPortionG_Positive", "\"DefaultPortionG\" > 0");

                            t.HasCheckConstraint("CK_Foods_FatG_NonNegative", "\"FatG\" >= 0");

                            t.HasCheckConstraint("CK_Foods_FiberG_NonNegative", "\"FiberG\" >= 0");

                            t.HasCheckConstraint("CK_Foods_Kcal_NonNegative", "\"Kcal\" >= 0");

                            t.HasCheckConstraint("CK_Foods_ProteinG_NonNegative", "\"ProteinG\" >= 0");

                            t.HasCheckConstraint("CK_Foods_SodiumMg_NonNegative", "\"SodiumMg\" >= 0");

                            t.HasCheckConstraint("CK_Foods_SugarG_NonNegative", "\"SugarG\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.FoodAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId", "Language")
                        .HasDatabaseName("IX_FoodAliases_FoodId_Language");

                    b.HasIndex("Language", "NormalizedAlias")
                        .IsUnique()
                        .HasDatabaseName("IX_FoodAliases_Language_NormalizedAlias");

                    b.ToTable("FoodAliases");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.LeaderboardSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AveragePace")
                        .HasColumnType("double precision");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<long?>("CompletionSpeed")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("TerritoryCount")
                        .HasColumnType("integer");

                    b.Property<double?>("TerritoryScore")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalDistance")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "SnapshotDate")
                        .HasDatabaseName("IX_LeaderboardSnapshots_ChallengeId_SnapshotDate");

                    b.HasIndex("SnapshotDate", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_LeaderboardSnapshots_Global_SnapshotDate_UserId")
                        .HasFilter("\"ChallengeId\" IS NULL");

                    b.HasIndex("ChallengeId", "SnapshotDate", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_LeaderboardSnapshots_ChallengeId_SnapshotDate_UserId");

                    b.ToTable("LeaderboardSnapshots");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("IX_Meals_LoggedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Meals_UserId");

                    b.HasIndex("UserId", "LoggedAt")
                        .HasDatabaseName("IX_Meals_UserId_LoggedAt");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.MealFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("IX_MealFoods_FoodId");

                    b.HasIndex("MealId")
                        .HasDatabaseName("IX_MealFoods_MealId");

                    b.ToTable("MealFoods", t =>
                        {
                            t.HasCheckConstraint("CK_MealFoods_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageCadenceRpm")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision");

                    b.Property<int?>("BurnedCalories")
                        .HasColumnType("integer");

                    b.Property<Polygon>("ConvexHull")
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("ElevHighMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevLowMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalActivityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasHeartrate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double?>("Kilojoules")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxLng")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinLng")
                        .HasColumnType("double precision");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<LineString>("Route")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<string>("RouteMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SufferScore")
                        .HasColumnType("integer");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunDate")
                        .HasDatabaseName("IX_RunningActivities_RunDate");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_RunningActivities_StartTime");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RunningActivities_UserId");

                    b.HasIndex("UserId", "ExternalActivityId")
                        .IsUnique()
                        .HasDatabaseName("IX_RunningActivities_UserId_ExternalActivityId");

                    b.ToTable("RunningActivities", t =>
                        {
                            t.HasCheckConstraint("CK_RunningActivities_AverageSpeed_NonNegative", "\"AverageSpeed\" >= 0");

                            t.HasCheckConstraint("CK_RunningActivities_DistanceMeters_NonNegative", "\"DistanceMeters\" >= 0");

                            t.HasCheckConstraint("CK_RunningActivities_ElapsedTimeSeconds_NonNegative", "\"ElapsedTimeSeconds\" >= 0");

                            t.HasCheckConstraint("CK_RunningActivities_MovingTimeSeconds_NonNegative", "\"MovingTimeSeconds\" >= 0");

                            t.HasCheckConstraint("CK_RunningActivities_TotalElevationGain_NonNegative", "\"TotalElevationGain\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivityAnalytics", b =>
                {
                    b.Property<int>("RunningActivityId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ComputedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ElevationSummaryJson")
                        .HasColumnType("jsonb");

                    b.Property<double?>("FirstHalfPaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsNegativeSplit")
                        .HasColumnType("boolean");

                    b.Property<double?>("MovingTimeRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("PaceVariabilitySecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<string>("PerformanceInsightsJson")
                        .HasColumnType("jsonb");

                    b.Property<double?>("SecondHalfPaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.HasKey("RunningActivityId");

                    b.ToTable("RunningActivityAnalytics", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivitySplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("ElapsedTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<double>("ElevationDifferenceMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<double>("PaceSecondsPerKm")
                        .HasColumnType("double precision");

                    b.Property<int>("RunningActivityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunningActivityId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("IX_RunningActivitySplits_ActivityId_Ordinal");

                    b.ToTable("RunningActivitySplits", t =>
                        {
                            t.HasCheckConstraint("CK_RunningActivitySplits_DistanceMeters_NonNegative", "\"DistanceMeters\" >= 0");

                            t.HasCheckConstraint("CK_RunningActivitySplits_PaceSecondsPerKm_NonNegative", "\"PaceSecondsPerKm\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CurrentOwnerScoreSnapshot")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<DateTime?>("CurrentOwnerSince")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurrentOwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("GeometryCells")
                        .HasColumnType("jsonb");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnershipTargetPercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CurrentOwnerUserId")
                        .HasDatabaseName("IX_Territories_CurrentOwnerUserId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Territories_PublicId");

                    b.ToTable("Territories", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("H3Index")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryId")
                        .HasDatabaseName("IX_TerritoryCells_TerritoryId");

                    b.HasIndex("TerritoryId", "H3Index")
                        .IsUnique()
                        .HasDatabaseName("IX_TerritoryCells_TerritoryId_H3Index");

                    b.ToTable("TerritoryCells", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryOwnershipHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ActionRunId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ActionScore")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("NewOwnerUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousOwnerUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionRunId")
                        .HasDatabaseName("IX_territory_ownership_history_action_run_id");

                    b.HasIndex("PreviousOwnerUserId");

                    b.HasIndex("NewOwnerUserId", "ActionAt")
                        .HasDatabaseName("IX_territory_ownership_history_new_owner_action_at");

                    b.HasIndex("TerritoryId", "ActionAt")
                        .HasDatabaseName("IX_territory_ownership_history_territory_action_at");

                    b.HasIndex("TerritoryId", "ActionRunId")
                        .IsUnique()
                        .HasDatabaseName("UQ_territory_ownership_history_territory_run");

                    b.ToTable("territory_ownership_history", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryUnlockCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAll")
                        .HasColumnType("boolean");

                    b.Property<double>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UnlockType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryId")
                        .HasDatabaseName("IX_TerritoryUnlockConditions_TerritoryId");

                    b.ToTable("TerritoryUnlockConditions", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("StravaAccessToken")
                        .HasColumnType("text");

                    b.Property<long?>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StravaConnectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StravaRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StravaTokenExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("IX_UserBadges_BadgeId");

                    b.HasIndex("EarnedAtUtc")
                        .HasDatabaseName("IX_UserBadges_EarnedAtUtc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserBadges_UserId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserBadges_UserId_BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProgressCalories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("ProgressDistanceMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<double?>("TerritoryScore")
                        .HasColumnType("double precision");

                    b.Property<long?>("TotalDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserChallenges_UserId_ChallengeId");

                    b.HasIndex("UserId", "Completed")
                        .HasDatabaseName("IX_UserChallenges_UserId_Completed");

                    b.ToTable("UserChallenges", t =>
                        {
                            t.HasCheckConstraint("CK_UserChallenges_ProgressCalories_NonNegative", "\"ProgressCalories\" >= 0");

                            t.HasCheckConstraint("CK_UserChallenges_ProgressDistanceMeters_NonNegative", "\"ProgressDistanceMeters\" >= 0");
                        });
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserTerritory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("OwnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryId");

                    b.HasIndex("UserId", "TerritoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserTerritories_UserId_TerritoryId");

                    b.ToTable("UserTerritories", (string)null);
                });

            modelBuilder.Entity("GradProject.Domain.Entities.AchievementEvent", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.ConsumedFood", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.DailySummary", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.FoodAlias", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Meal", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.MealFood", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.Meal", "Meal")
                        .WithMany("MealFoods")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Profile", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GradProject.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivity", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivityAnalytics", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.RunningActivity", "RunningActivity")
                        .WithOne("Analytics")
                        .HasForeignKey("GradProject.Domain.Entities.RunningActivityAnalytics", "RunningActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningActivity");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivitySplit", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.RunningActivity", "RunningActivity")
                        .WithMany("Splits")
                        .HasForeignKey("RunningActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningActivity");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Territory", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.User", "CurrentOwnerUser")
                        .WithMany()
                        .HasForeignKey("CurrentOwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentOwnerUser");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryCell", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Territory", "Territory")
                        .WithMany("TerritoryCells")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryOwnershipHistory", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.RunningActivity", "ActionRun")
                        .WithMany()
                        .HasForeignKey("ActionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.User", "NewOwnerUser")
                        .WithMany()
                        .HasForeignKey("NewOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.User", "PreviousOwnerUser")
                        .WithMany()
                        .HasForeignKey("PreviousOwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GradProject.Domain.Entities.Territory", "Territory")
                        .WithMany("OwnershipHistory")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionRun");

                    b.Navigation("NewOwnerUser");

                    b.Navigation("PreviousOwnerUser");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.TerritoryUnlockCondition", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Territory", "Territory")
                        .WithMany("UnlockConditions")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserChallenge", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.UserTerritory", b =>
                {
                    b.HasOne("GradProject.Domain.Entities.Territory", "Territory")
                        .WithMany("UserTerritories")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Territory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealFoods");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.RunningActivity", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.Territory", b =>
                {
                    b.Navigation("OwnershipHistory");

                    b.Navigation("TerritoryCells");

                    b.Navigation("UnlockConditions");

                    b.Navigation("UserTerritories");
                });

            modelBuilder.Entity("GradProject.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
